### ISSUE TITLE
Regression in commit 0af1c6cec6efb1d1bdc8730b5d05b10024c704d3

### ISSUE THREAD

**Issue by scd31** [adamgreig/labrador-ldpc#14]
Disclaimer: I've looked into this very little (just noticed before going to bed)

Can reproduce by doing the following:

1. Run tests on this library: https://gitlab.scd31.com/cats/ham-cats
2. Observe all tests pass
3. In the Cargo.toml, change the rev to 0af1c6cec6efb1d1bdc8730b5d05b10024c704d3
4. Observe two LDPC tests fail (seems that the soft decoder no longer works properly)

I suspect there's a bug somewhere from the refactoring, but a quick glance didn't reveal anything. I'll take a closer look in the next few days

**Comment by scd31** [comment]
Aha - found the issue. I'm reusing the `working` area for multiple decode calls, and it looks like in that commit we removed `for w in &mut working[..] { *w = T::zero() }`

Calling it a regression is a bit strong on my part - my bad. Do we want to revert this or should I update my code to zero it before each run? I think if we leave it as-is, we should add a doc comment mentioning the working area must be zeroed.

**Comment by adamgreig** [comment]
Nice catch, thanks. I hadn't intended to commit that line, I was working on some non-zero working area initialisation (in principle some of the messages can be initialised to more useful values, but so far I couldn't detect any meaningful difference). I think it's best if we keep the WA zero-init for now, so I'll restore that and re-release.

**Comment by adamgreig** [comment]
Published at v1.2.1, thanks again.
