### ISSUE TITLE
#[repr(C)] for LDPCCode

### ISSUE THREAD

**Issue by chairmanwow** [adamgreig/labrador-ldpc#3]
Any chance at adding a #[repr(C)] annotation to LDPCCode? It's causing a warning when compiling. Obviously, not a big deal to get the warnings. I don't know enough about how Rust enums match up with C enums to know whether or not this could, in theory, break. I think I remember reading that the default enum layout in Rust basically has no guarantees unless you specify a preferred layout.

```
warning: `extern` fn uses type `LDPCCode`, which is not FFI-safe
   --> src/lib.rs:229:11
    |
229 |     code: LDPCCode,
    |           ^^^^^^^^ not FFI-safe
    |
    = help: consider adding a `#[repr(C)]`, `#[repr(transparent)]`, or integer `#[repr(...)]` attribute to this enum
    = note: enum has no representation hint
```

Thanks @adamgreig. This library is carrying water for me for sure. 

As an aside, I'm actually writing Java JNI into this library so it can get called from Java and Clojure. The Rust JNI crate gels very nicely with this library. Obviously it wrecks `no_std` when you use the JNI crate. If you're at all interested, I'm happy to share the code. 

Lemme know if you want a pull request.

**Comment by adamgreig** [comment]
Thanks for the report! I guess this warning was added recently... or, ok, sometime in the last few years anyway. I've released v1.0.1 with the repr(C) fix, which seems to do the trick. I'm glad to hear it's working out for you and even from JNI, cool!
