### ISSUE TITLE
decode_ms with some bits I know are correct

### ISSUE THREAD

**Issue by scd31** [adamgreig/labrador-ldpc#9]
Hello,

I'm using this library with packets that are sometimes smaller than my LDPC code requires. To work around this, I'm padding the data with `0xAA`, then I'm transmitting the data (without padding) and parity. On the decode side, I pad the data again and run through the usual decode flow.

I'm now wanting to implement soft decoding. I know the `0xAA` bits can't flip, since they're hardcoded and not sent over the channel. Should I just set these bits to `DecodeFrom::maxval()`? I think that would be the most elegant, except for this in the documentation:

> Internally, variables of type T are used to accumulate messages, so it is useful to leave some headroom in T after the range of your LLRs. For T=i8 you might assign -32 to 31 for LLR inputs, so that several full-scale messages can be accumulated before saturation occurs. On floating point types this is less of a concern.

I'm unsure if this affects me here since I know these padding bits will never need to be corrected.

Thanks!

**Comment by adamgreig** [comment]
Interesting question. I'm afraid I don't remember the specifics, but I think you should be fine using `maxval()` for the bits that definitely won't need correcting. Still, give it a few test runs to check you're getting the performance you expect.

**Comment by scd31** [comment]
Thanks!
